gitRepoUrl = "https://github.com/zythdotdev/roblox-utility"
gitSourceBranch = "main"

[home]
enabled = false
includeReadme = false

[docusaurus]
tagline = "A collection of strictly typed utility modules for Roblox"

[footer]
style = "dark"

[[classOrder]]
section = "Event"
classes = ["Event", "EventConnection"]

[[classOrder]]
section = "Connection"
classes = ["Connection", "NetworkEvent", "NetworkRequest", "NetworkValue"]