[package]
name = "zythdotdev/value"
description = "Value tracking implementation for Roblox"
version = "2.0.0"
license = "MIT"
authors = ["zythdotdev (https://zyth.dev)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Event = "zythdotdev/event@2.0.0"