[package]
name = "zythdotdev/event"
description = "Signal implementation for Roblox"
version = "2.0.1"
license = "MIT"
authors = ["zythdotdev (https://zyth.dev)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"